<?xml version="1.0" encoding="utf-8"?><Database Name="Pet_Shop" Class="QLSHOPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DIMAN;Initial Catalog=Pet_Shop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Pet_ShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="locations" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="id" OtherKey="category_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="locations" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_Product" Member="Products" ThisKey="id" OtherKey="menu_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Options" Member="Options">
    <Type Name="Option">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Option_Product" Member="Products" ThisKey="id" OtherKey="options_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Producer" Member="Producers">
    <Type Name="Producer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="locations" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producer_Product" Member="Products" ThisKey="id" OtherKey="producer_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="id" OtherKey="role_id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Tokens" Member="Tokens">
    <Type Name="Token">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="token" Member="token1" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Token" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Details" Member="Order_Details">
    <Type Name="Order_Detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_money" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="User_Order_Detail" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="Order_Order_Detail" Member="Order" ThisKey="order_id" OtherKey="id" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Order_Detail" Member="Product" ThisKey="product_id" OtherKey="id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="User_Token" Member="Tokens" ThisKey="id" OtherKey="user_id" Type="Token" />
      <Association Name="User_Order_Detail" Member="Order_Details" ThisKey="id" OtherKey="user_id" Type="Order_Detail" />
      <Association Name="User_FeedBack" Member="FeedBacks" ThisKey="id" OtherKey="user_id" Type="FeedBack" />
      <Association Name="User_Order" Member="Orders" ThisKey="id" OtherKey="user_id" Type="Order" />
      <Association Name="User_Detail_Order" Member="Detail_Orders" ThisKey="id" OtherKey="user_id" Type="Detail_Order" />
      <Association Name="Role_User" Member="Role" ThisKey="role_id" OtherKey="id" Type="Role" IsForeignKey="true" />
      <Association Name="Role1_User" Member="Role1" ThisKey="role_id" OtherKey="id" Type="Role1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FeedBack" Member="FeedBacks">
    <Type Name="FeedBack">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="nVarChar(1000)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_FeedBack" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="order_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_money" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Order_Detail" Member="Order_Details" ThisKey="id" OtherKey="order_id" Type="Order_Detail" />
      <Association Name="Order_Detail_Order" Member="Detail_Orders" ThisKey="id" OtherKey="order_id" Type="Detail_Order" />
      <Association Name="User_Order" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="Product_Order" Member="Product" ThisKey="product_id" OtherKey="id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Detail_Order" Member="Detail_Orders">
    <Type Name="Detail_Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Detail_Order" Member="Order" ThisKey="order_id" OtherKey="id" Type="Order" IsForeignKey="true" />
      <Association Name="User_Detail_Order" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="Product_Detail_Order" Member="Product" ThisKey="product_id" OtherKey="id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="producer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="options_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inventory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="outstanding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deleted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_Order_Detail" Member="Order_Details" ThisKey="id" OtherKey="product_id" Type="Order_Detail" />
      <Association Name="Product_Order" Member="Orders" ThisKey="id" OtherKey="product_id" Type="Order" />
      <Association Name="Product_Detail_Order" Member="Detail_Orders" ThisKey="id" OtherKey="product_id" Type="Detail_Order" />
      <Association Name="Category_Product" Member="Category" ThisKey="category_id" OtherKey="id" Type="Category" IsForeignKey="true" />
      <Association Name="Menu_Product" Member="Menu" ThisKey="menu_id" OtherKey="id" Type="Menu" IsForeignKey="true" />
      <Association Name="Option_Product" Member="Option" ThisKey="options_id" OtherKey="id" Type="Option" IsForeignKey="true" />
      <Association Name="Producer_Product" Member="Producer" ThisKey="producer_id" OtherKey="id" Type="Producer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Role1s">
    <Type Name="Role1">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Role1_User" Member="Users" ThisKey="id" OtherKey="role_id" Type="User" />
    </Type>
  </Table>
</Database>